### PR TITLE
Update system requirements for Contao 5 under PHP 8.3+

### PR DESCRIPTION
**Pull request by fritzmg**
See https://github.com/contao/contao/issues/6983#issuecomment-2014041710

I decided to simplify the table as you would need to employ the system requirements of Contao 4.13 anyway, if you want to update from 4.4+ to 4.13 for example.

### CODE REVIEW

**Review by netzarbeiter — APPROVED** [review]
Thank you, Fritz

**Comment by fritzmg** [comment]
@leofeyer @ausi should we merge this? Or wait until we resolved this in Contao itself.

**Comment by ausi** [comment]
> should we merge this? Or wait until we resolved this in Contao itself.

I think we should merge it. We only need to fix it in Contao itself if this causes issues for a larger number of users, right?

**Comment by leofeyer** [comment]
Correct. 👍

**Pull request merged**
