### PR TITLE
Add replacement information for postLogin hook

### PR DESCRIPTION
**Pull request by dmolineus**
Add hint to use the proper symfony event

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, I don't think this is correct, is it? For the `postAuthenticate` hook the replacement would be `security.authentication.success` while for the `postLogin` hook the replacement would be `security.interactive_login`, is it not?

**Comment by dmolineus** [comment]
You're right. I accidentely clicked on the wrong edit link.

**Comment by fritzmg** [comment]
I'll keep this open anyway to confirm ;)

**Comment by fritzmg** [comment]
Updated in 505c3f50de3f666cdf1110b9050607d03de841f2 and 4c80274959d326e306b8df1882079879fcbfe36e

**Comment by dmolineus** [comment]
Thanks. I just was about to adjust the pr and create a new one for `postLogin`

**Pull request closed without merging**
