### PR TITLE
Load Contao modules automatically, if available

### PR DESCRIPTION
**Pull request by bytehead**
See #310.

@fritzmg WDYT?

### CODE REVIEW

**Comment by fritzmg** [comment]
lgtm :). May be add a note about what that new code actually does? Doesn't need to go into detail, just that it would automatically load any Contao 3 extensions, if installed.

**Comment by bytehead** [comment]
> May be add a note about what that new code actually does? Doesn't need to go into detail, just that it would automatically load any Contao 3 extensions, if installed.

Sure, it was more like a proposal 🙃

**Comment by bytehead** [comment]
Updated in 2c44afc.

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Thank you @bytehead

**Pull request merged**
