### PR TITLE
English translation: guides

### LINKED ISSUE #511: English translation: guides
See [CONTRIBUTING.md#manual-english-translation-revision](https://github.com/contao/docs/blob/master/CONTRIBUTING.md#manual-english-translation-revision)

### PR DESCRIPTION
**Pull request by fkaminski**
Closes #511

- with the help of free deepl service
- checked/solved format issues
- solved links
- create new/rename images/screenshots

Except for the "Laragon" Chapter (only format issues solved). 
Maybe we could ask the original author for new screenshot (en) after merging ...

### CODE REVIEW

**Comment by fritzmg** [comment]
Awesome 👍 

I looked over everything and directly made some adjustments. @fkaminski I don't suppose you could also provide English screenshots for the Laragon installation? 😁 🙈

**Comment by fkaminski** [comment]
> Awesome 👍
> 
> I looked over everything and directly made some adjustments. @fkaminski I don't suppose you could also provide English screenshots for the Laragon installation? 😁 🙈

No, sorry. Maybe we could ask the original author for new screenshot (en) after merging ...

**Comment by fritzmg** [comment]
@netzarbeiter what do you think? Should we merge this without English screenshots for the Laragon guide?

**Comment by netzarbeiter** [comment]
Merge it without English screenshots. Thank you very much for the pull request and proofreading it.

**Pull request merged**
