### PR TITLE
Replace absolute flag with attribute

### PR DESCRIPTION
**Pull request by ausi**
See https://github.com/contao/contao/pull/3146

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by Toflar** [comment]
Ah, maybe I was too quick merging this! This doesn't work in 4.9, does it?
The `::absolute` is actually mentioned further down. And if we want this adjustment, we also need it in English.

**Comment by ausi** [comment]
> This doesn't work in 4.9, does it?

Yes, sorry 🙈 Was changed in 4.12: https://github.com/contao/contao/commit/36dc94777fd1da8a91eed022804869f0f898fd49

Will do a folloup PR

**Comment by fritzmg** [comment]
@Toflar please let @netzarbeiter handle merges into the manual, as he also takes care of it getting translated in case the translation was not provided.

**Comment by Toflar** [comment]
I did check for the translation, don't worry :)

**Pull request merged**
