### PR TITLE
Do not use blacklist and whitelist

### PR DESCRIPTION
**Pull request by fritzmg**
Docs PR for https://github.com/contao/contao/pull/1798

Btw. @Toflar shouldn't we also document the `COOKIE_REMOVE_FROM_DENY_LIST`/`COOKIE_DISABLE_FROM_BLACKLIST` env vars?

### CODE REVIEW

**Review by Toflar — CHANGES_REQUESTED** [review]
Maybe we should write in 4.8 and 4.9? Or don't we care because unmaintained version?

> Btw. @Toflar shouldn't we also document the COOKIE_REMOVE_FROM_DENY_LIST/COOKIE_DISABLE_FROM_BLACKLIST env vars?

Only the first one, it's a new feature in 4.10 only.

**Comment by fritzmg** [comment]
> Or don't we care because unmaintained version?

We don't care, because unmaintained, yes.

> Only the first one, it's a new feature in 4.10 only.

Ah ok, did not realise. Then a ticket/PR for the new feature is missing, can you create one?

**Comment by Toflar** [comment]
Done in https://github.com/contao/docs/issues/463

**Comment by Toflar** [comment]
You can turn this into a regular PR then, because the statement is correct.

**Pull request merged**
