### PR TITLE
Split Contao 4.4.* / 4.9* in a Symfony application docs into separate pages

### PR DESCRIPTION
**Pull request by bytehead**
See #300.

Todo:

- [x] Contao 4.4 LTS
- [x] Contao 4.9 LTS

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
`contao-4.9.md` still mentions the following:

> And change the default and fallback language to `de`, so the install tool comes
up translated. In order to do so, change `en` to `de` in `config/translation.yaml`.

But as far as I understood it, in your tutorial, the Install Tool isn't used anymore (nor is it needed, right?). So may be this paragraph needs to be rewritten slightly.

**Comment by fritzmg** [comment]
Btw. there is a PR for tabs for the Learn Theme: https://github.com/matcornic/hugo-theme-learn/pull/386

So may be in the future we can consolidate it into one article again.

**Comment by bytehead** [comment]
> But as far as I understood it, in your tutorial, the Install Tool isn't used anymore (nor is it needed, right?). So may be this paragraph needs to be rewritten slightly.

It's still with the use of the install tool as you cannot create an admin user on the CLI (see https://github.com/contao/contao/pull/1463). I'll update the docs accordingly, after the command is available.

See https://github.com/contao/docs/pull/307/files#diff-987fb580f1f4826e15ddf477dedff4eaR256

**Comment by bytehead** [comment]
Yeah, let me know when the tab feature is available! 🎉

**Comment by fritzmg** [comment]
> It's still with the use of the install tool as you cannot create an admin user on the CLI (see [contao/contao#1463](https://github.com/contao/contao/pull/1463)). I'll update the docs accordingly, after the command is available.

Ah yes, but in the 4.9 version, you don't add the Install Tool's routes to the `routes.yaml`. This has still to be done, or not?

**Comment by bytehead** [comment]
Yes, good catch. I've updated it.

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Thank you @bytehead :)

**Pull request merged**
