### PR TITLE
Update settings.en.md

### PR DESCRIPTION
**Pull request by Tastaturberuf**
Double percent sign is wrong, should be `@` =>`%40`

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
`%` needs to be double encoded with `%%` in YAML files, do they not?

**Comment by Tastaturberuf** [comment]
Not in this case, because the urlencode starts first and in this example the final result is `smtps://email%@example.org:foobar@example.org`. An hour ago i run in this error.

**Comment by Tastaturberuf** [comment]
Symfony dosn't mention double encoding too: https://symfony.com/doc/5.x/mailer.html#transport-setup

**Comment by Tastaturberuf** [comment]
The error was (user and domain changed):
```
In EsmtpTransport.php line 198:

  Failed to authenticate on SMTP server with username "user%@domain.de" using the following authenticators: "LOGIN", "PLAIN", "XOAUTH2". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with me
  ssage "535-5.7.8 Username and Password not accepted. For more information, go to
  535 5.7.8  https://support.google.com/mail/?p=BadCredentials c2-20020adfe742000000b003366a9cb0d1sm1971082wrn.92 - gsmtp".". Authenticator "PLAIN" returned "Expected response code "235" but got code "535", with message "535-5.7.8 Use
  rname and Password not accepted. For more information, go to
  535 5.7.8  https://support.google.com/mail/?p=BadCredentials c2-20020adfe742000000b003366a9cb0d1sm1971082wrn.92 - gsmtp".". Authenticator "XOAUTH2" returned "Expected response code "235" but got code "334", with message "334 eyJzdGF
  0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==".".

```

**Comment by fritzmg** [comment]
Did you use environment variables or write the credentials directly into the `config.yaml`?

**Comment by Tastaturberuf** [comment]
In the `MAILER_DSN`.

**Comment by fritzmg** [comment]
The double encoding requirement only applies to YAML.

// (accidentally closed)

**Comment by Tastaturberuf** [comment]
Ok, then we can close this anyway. Thansk for clearing that topic. 

https://docs.contao.org/manual/en/system/settings/#e-mail-sending-configuration

its written here, but there are so many boxes i have overlook it.

**Pull request closed without merging**
