### PR TITLE
Change default from boolean

### PR DESCRIPTION
**Pull request by zonky2**
boolean is TINYINT and strict mode send error without default value

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, I cannot reproduce. What exact error are you getting?

**Comment by zonky2** [comment]
`General error: 1364 Field 'xy' doesn't have a default value`

**Comment by fritzmg** [comment]
There must be a mistake on your end. When using

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['fields']['foobar'] = [
    'sql' => [
        'type' => 'boolean',
        'default' => false,
    ],
];
```

then `contao:migrate` will execute

```
ALTER TABLE tl_content ADD foobar TINYINT(1) DEFAULT '0' NOT NULL
```

**Comment by zonky2** [comment]
ok. - I´ll check this

**Comment by fritzmg** [comment]
May be the field was already present in your database? But even then: the default value change should be picked up by Doctrine and thus change during `contao:migrate`.

**Pull request closed without merging**
