### PR TITLE
Fix breadcrumbs tablet view

### PR DESCRIPTION
**Pull request by fkaminski**
The "Diese Seite bearbeiten" (only DE) causes the following display in tablet view. 

image

If we would shorten the text it fits again.

image

### CODE REVIEW

**Comment by fritzmg** [comment]
Would the same issue occur if you go one level deeper?

**Comment by fkaminski** [comment]
> Would the same issue occur if you go one level deeper?

Yepp (even though the breadcrumbs shortens "..."). 

image

Even then its fits with the fix.

image

**Comment by fkaminski** [comment]
Alternatively we could change the media query ?
**from:**

```
@media only all and (max-width: 47.938em) {
  #breadcrumbs .links, #top-github-link-text {
      display: none;
  }
}

```
**to:** (symbol only) 

```
@media only all and (max-width: 47.938em) {
  #breadcrumbs .links {
      display: none;
  }
}

@media only all and (max-width: 64em) {
  #top-github-link-text {
      display: none;
  }
}
```

**Comment by fritzmg** [comment]
I am fine with changing the wording of the link. However, it does not solve the problem completely. The issue is that the theme uses float left/right for these things - instead of flex or grid for example.

**Review by netzarbeiter — APPROVED** [review]
Thank you, Franko

**Pull request merged**
