### PR TITLE
Fix anchor links

### PR DESCRIPTION
**Pull request by dmolineus**
This pull request fixes the broken anchor links introduced by #243. 

Since hugo 0.60 you can configure the markdown parser which also changed the way how headings got converted to ids. Since hugo 0.62.2 there is a new setting `autoHeadingIDType` to preserve the old behaviour.

 - https://gohugo.io/getting-started/configuration-markup/#goldmark
 - https://gohugo.io/news/0.62.2-relnotes/

This PR fixes the anchor ids and sets the new option to preserve the old behaviour.

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, but in your PR you set the old behaviour _and_ you had to change all the anchor links regardless? Ah, or were the previous IDs in your PR already in the new format?

**Comment by dmolineus** [comment]
The IDs in my pr are in the new format (GitHub style which is the default since Hugo 0.60). You're using Hugo 0.58 to build the docs, so my added anchor links are broken at the moment.

I noticed that after the pr got merged and published to docs.contao.org.

I suggest also to update to latest Hugo version when building the docs

**Comment by fritzmg** [comment]
> I suggest also to update to latest Hugo version when building the docs

Yeah, definitely. Will have to test everything though, before updating.

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Thank you @dmolineus

**Pull request merged**
