### PR TITLE
add makelrmodul to extensions

### PR DESCRIPTION
**Pull request by MDevster**

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
Please also provide the English version :)

**Comment by zonky2** [comment]
```diff
- add makelrmodul to extensions
+ add maklermodul to extensions
```
:D

**Comment by MDevster** [comment]
> Please also provide the English version :)

is there a link for the english version?

**Comment by fritzmg** [comment]
> is there a link for the english version?

Not yet, the English version of the manual is still a work in progress.

**Review by fritzmg — APPROVED** [review]

**Comment by netzarbeiter** [comment]
Thank you @MDevster

**Pull request merged**
