### PR TITLE
remove object return type

### PR DESCRIPTION
**Pull request by Tastaturberuf**
Object return type is available from PHP 7.2 
Contao 4.9 requires minimum 7.1

### CODE REVIEW

**Comment by netzarbeiter** [comment]
Contao 4.9 requires minimum 7.2
https://docs.contao.org/manual/de/installation/systemvoraussetzungen/

**Comment by fritzmg** [comment]
> Contao 4.9 requires minimum 7.1

Contao 4.9 requires at least PHP 7.2 ;). But the documentation was written with PHP 7.1 in mind, so I would remove it. Otherwise we could use the `object` type in more places.

**Review by fritzmg — APPROVED** [review]

**Comment by Tastaturberuf** [comment]
Its 24 days ago  switched to 7.2: https://github.com/contao/managed-edition/commit/b6ac6712054c3301d34eb8b4fa5a01b103a09d21
my composer.json is still at 7.1

**Comment by fritzmg** [comment]
> my composer.json is still at 7.1

In your root `composer.json` you define the minimum required PHP version for your project. The minimum PHP version of each package you use in your project (e.g. the `contao/core-bundle`) is defined in the `composer.json` of each package.

**Comment by Tastaturberuf** [comment]
i know, its from `create-project contao/managed-edition` earlier than 24 days ago. 

Its from 2020-05-01 and at this time the requirement was 7.1

now i have changed it to 7.2

**Pull request merged**
