### PR TITLE
Delete Contao call

### PR DESCRIPTION
**Pull request by zonky2**

### CODE REVIEW

**Review by netzarbeiter — APPROVED** [review]
Thank you, Ingolf

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/commit/ec9f20667ca01fdfe163d4bc6dacc641d25a83b2

**Comment by fiedsch** [comment]
For a reader that does not know the history of how Contao calls where held, the question might arise: "what does Mumble have to do with Contao and why do we have it in the Contao documentation?"

A note like "Mumble was used to hold the Contao calls until replaced by Slack huddles" right at the start of the text might clear this.  

What do you think?

**Comment by netzarbeiter** [comment]
Thank you for your feedback.

Don't you think the note on the top of the page does the trick?

**Comment by fiedsch** [comment]
Yes, sure. I was only reading the diff showing @zonky2's changes and did not see the note. My bad :-(

**Pull request merged**
