### PR TITLE
Encode the SMTP username

### PR DESCRIPTION
**Pull request by leofeyer**
I‘m not 100% sure but I think the SMTP username cannot contain the unencoded `@` character, can it?

### CODE REVIEW

**Comment by netzarbeiter** [comment]
I have tested the following two versions:

`website1: smtps://test%40example.com:%5D%23wWFmxH%3Ahpd4@mail.test.ch:465`

`website2: smtps://test@examle.com:kGQsbDg5UPnq%2AnK@mail.test.ch:465`

Result when clearing the catch of website1

```
In ParameterBag.php line 93:
                                                                 
You have requested a non-existent parameter "40example.com:".  
```

Conclusion: it is not working with the encoded `@`.

**Comment by leofeyer** [comment]
That‘s strange, because Symfony explicitly warns about it in their [docs](https://symfony.com/doc/current/mailer.html#transport-setup):

**Comment by ausi** [comment]
> `website1: smtps://test%40example.com:%5D%23wWFmxH%3Ahpd4@mail.test.ch:465`

the `%` needs to be encoded itself I think, so this should work:
`website1: smtps://test%%40example.com:%%5D%%23wWFmxH%%3Ahpd4@mail.test.ch:465`

**Comment by leofeyer** [comment]
Of course, it is YAML. 🤦‍♂️ Fixed in 5f8e3a3ff8e33e679c3d7b798c81d8c3c0d55912.

**Review by netzarbeiter — APPROVED** [review]

**Comment by netzarbeiter** [comment]
Thank you, Leo

https://github.com/contao/docs/commit/8b17b1feb2cc8da80f4b5c7a0d29bb601174c68e

**Pull request merged**
