### PR TITLE
Bilder werden nicht angezeigt

### PR DESCRIPTION
**Pull request by contaoacademy**
https://community.contao.org/de/showthread.php?77420-Keine-Bilder-nach-Update-von-4-4-auf-4-9&p=521574&viewfull=1#post521574

### CODE REVIEW

**Review by netzarbeiter — APPROVED** [review]

**Comment by netzarbeiter** [comment]
Vielen Dank, @contaoacademy.

**Comment by contaoacademy** [comment]
Thx @netzarbeiter. I noticed, that I have missed a dot at the end of the sentence. Maybe you could add this "dot".

**Comment by netzarbeiter** [comment]
Done

**Review by fritzmg — COMMENTED** [review]
This PR is missing the English translation. We should not merge a PR before the English translation is finished. Or we should create a separate issue for the English translation as a reminder.

@contaoacademy could you create an issue for the English translation for this? Or provide it in a PR yourself ;)

**Comment by contaoacademy** [comment]
https://github.com/contao/docs/pull/536

**Pull request merged**
