### PR TITLE
Add shortcode expand to contribute.md

### PR DESCRIPTION
**Pull request by fkaminski**
You were too fast with the merging :-)

I would like, for the sake of overview, also list the shortcode expand. 
(Even if I know that "someone" does not like this :-).)

Therefore: As you like ...

### CODE REVIEW

**Comment by fritzmg** [comment]
> You were too fast with the merging :-)

If the PR was not ready, you need to mark it as a draft.

**Comment by fritzmg** [comment]
But I was just thinking: I don't think we should add any of this actually. This is already documented in the documentation of the theme. There is no need to duplicate already existing documentation and then maintain said duplication. I will adjust the `CONTRIBUTING.md` afterwards accordingly.

**Comment by fkaminski** [comment]
> This is already documented in the documentation of the theme.

Certainly. But some of the Hugo theme documentation is/was implemented faster than available for our documentation (example shortcode tabs) ... 
Therefore ... ?

**Comment by fritzmg** [comment]
> But some of the Hugo theme documentation is/was implemented faster than available for our documentation (example shortcode tabs) ...

Not sure what you mean?

**Comment by fkaminski** [comment]
> > But some of the Hugo theme documentation is/was implemented faster than available for our documentation (example shortcode tabs) ...
> 
> Not sure what you mean?

I meant that we should mention the shortcodes that actually exist, regardless of the Hugo theme documentation. These can deviate quite temporally. This was the case with the tabs, for example. They were first available in the hugo theme and were later included in our documentation.

**Comment by fritzmg** [comment]
If someone wants to use a new feature from the Learn theme, then they can open an issue so that we can update the theme accordingly. I don't see a point in duplicating the documentation from the used theme. It's just more work and maintenance with no gain.

**Comment by fkaminski** [comment]
OK

**Pull request closed without merging**
