### PR TITLE
added file path for Contao <4.8

### PR DESCRIPTION
**Pull request by Teetrinker**
`app/Resources/contao/dca/`
vs.
`contao/dca/`

### CODE REVIEW

**Comment by fritzmg** [comment]
That's not necessary. The difference between Contao 4.4 and 4.9 is explained here: https://docs.contao.org/dev/getting-started/starting-development/#structure

**Comment by Teetrinker** [comment]
I didn't find that information when reading the doc. While reading about the dca, I had no clue paths could differ.

I don't know the best way to do this, but this little notice about differing paths should be more accessible for people diving straight in.

**Comment by fritzmg** [comment]
Well, people diving straight in should may be also use the most recent Contao version ;). The `contao/` path is referenced in many, many places obviously, more than you have covered in your PR. Always referencing

```
app/Resources/contao/
```

and

```
contao/
```

seems superfluous to me.

We could of course _only_ reference `app/Resources/contao/`, since that will aways work - but we want people to use the best practice approach, not the legacy approach.

_But_, may be a short notice in these specific places are warranted.

**Comment by fritzmg** [comment]
I have now added more references to the folder structures in various places in 5a44c26

**Pull request closed without merging**
