### PR TITLE
Update config.md

### PR DESCRIPTION
**Pull request by Mynyx**
Add ``trusted_device`` cookie to ``COOKIE_WHITELIST``.

### CODE REVIEW

**Comment by fritzmg** [comment]
Based on the discussion in https://github.com/contao/contao/issues/1618

**Comment by Mynyx** [comment]
Currently, the trusted devices function wouldn't work if the cookie is not included in the whitelist.

**Edit:** Of course, this only applies if the whitelist is used at all.

**Comment by fritzmg** [comment]
> Currently, the trusted devices function wouldn't work if the cookie is not included in the whitelist.

This is a comment you should add in https://github.com/contao/contao/issues/1618, not here.

**Comment by Mynyx** [comment]
@Toflar I think this change would correctly describe the current situation?

**Review by Toflar — APPROVED** [review]
That's correct.

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Thank you @Mynyx :)

**Pull request merged**
