### PR TITLE
Update content element markdown

### PR DESCRIPTION
**Pull request by fkaminski**
Add "Markdown source"
Formatting "Markdown syntax" with expand layout

### CODE REVIEW

**Comment by netzarbeiter** [comment]
Thank you, Franko.

I do not want to hide information behind expand.
It is an additional and in my eyes unnecessary click.

Besides, we had discussed on slack that we prefer to put energy into non-existing content rather than "cleaning up" existing content.

**Comment by fkaminski** [comment]
This PR adds new content too. I can change the layout if you like? 
i am not in office until the end of next week and will Update as soon as possible.

**Comment by netzarbeiter** [comment]
That would be great.

**Review by netzarbeiter — APPROVED** [review]
Thank you, Franko

**Pull request merged**
