### PR TITLE
Use cronjob to label pull requests

### PR DESCRIPTION
**Pull request by Toflar**
See https://github.com/actions/labeler/issues/12 for details.

### CODE REVIEW

**Comment by fritzmg** [comment]
Shouldn't the interval be shorter? Chances are that I will always be faster 😁

**Comment by Toflar** [comment]
I didn't want to hammer GitHub but we can also shorten the interval. Suggestions?

**Comment by fritzmg** [comment]
May be 15 min? But yeah... auto-labeling isn't that important, so we might as well leave it at 1 hour, so as to not hammer GitHub and waste resources.

**Review by fritzmg — APPROVED** [review]

**Comment by Toflar** [comment]
I would leave it like that for now and see how it goes.

**Pull request merged**
