### PR TITLE
Add "Web Font Loader" Link (DE/EN)

### PR DESCRIPTION
**Pull request by fkaminski**
See: https://community.contao.org/de/showthread.php?82105-Contao-Schriften&p=552576&viewfull=1#post552576

### CODE REVIEW

**Comment by fritzmg** [comment]
Should we mention why the new web font loader might be better? We experienced that problem a lot actually.

**Comment by fkaminski** [comment]
> Should we mention why the new web font loader might be better? We experienced that problem a lot actually.

We could: 
Possibly with an info box entry with links to 
https://github.com/majodev/google-webfonts-helper/issues/98
or
https://webfontloader.altmann.de/about/#more

Maybe this would be too confusing for our documentation. Alternatively we just put the link to the new app?

What do you think?

**Comment by fkaminski** [comment]
For example:

Falls du nicht sicher bist welche der genannten Webapplikationen du benutzen solltest findest du hier einen Beitrag der die Unterschiede verdeutlicht.

If you are not sure which of the mentioned web applications you should use, here is a post that clarifies the differences.

Then with link to: https://webfontloader.altmann.de/about/#more

**Review by netzarbeiter — APPROVED** [review]
Thank you, Franko

**Pull request merged**
