### PR TITLE
Update insert-tags.en.md

### PR DESCRIPTION
**Pull request by heimseiten**

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
The `{{link::*}}` Insert Tag is meant to be used with page IDs. Does it really work like that?

**Comment by heimseiten** [comment]
Yes, the code written above is what I get. And:
Bildschirmfoto 2024-03-20 um 11 02 25

**Comment by heimseiten** [comment]
But perhaps two examples would also be good. One with a page ID and one with an external URL.

Unfortunately, a phone link doesn't seem to be working. Like: tel:0123456789

**Review by fritzmg — CHANGES_REQUESTED** [review]
I don't think this should be merged as is then. The `*` is a place holder for a Page ID or an absolute URL.

**Comment by heimseiten** [comment]
I agree. Thank you Fritz!

**Pull request closed without merging**
