### PR TITLE
Add Latest Version Infos

### PR DESCRIPTION
**Pull request by fkaminski**
An attempt to highlight current version information/changes in the manual. 
A new hugo shortcode "changelog" is used.

The goal would be later to highlight/add some feature highlights here too.

### CODE REVIEW

**Comment by fkaminski** [comment]
~~Probably we could simplify the regular expression in the "shortcode" - suggestions are welcome.~~

**Comment by fritzmg** [comment]
Hm, so this just shows the changelog from the most recent version?

image

I am not sure how useful this really is. @netzarbeiter wdyt?

**Comment by fkaminski** [comment]
> I am not sure how useful this really is.

Understood and makes sense. 
If such a thing should be desired in principle, 
one could possibly extend the shortcode (show the changes of the last x versions or all within an accordion etc.).

Furthermore, I wanted to add additional targeted FE highlights here 
(ala https://www.youtube.com/watch?v=xH_2XjqM2vc) - roughly. 

How exactly this could look graphically I do not know yet. Something like this:: 
https://portal.productboard.com/7pu88c9kpmqtzt8hwg6arujh/tabs/6-released

**Comment by fritzmg** [comment]
> Furthermore, I wanted to add additional targeted FE highlights here (ala https://www.youtube.com/watch?v=xH_2XjqM2vc) - roughly.
> 
> How exactly this could look graphically I do not know yet. Something like this:: https://portal.productboard.com/7pu88c9kpmqtzt8hwg6arujh/tabs/6-released

What does this have to do with this PR? I am really confused now 😁

**Comment by fkaminski** [comment]
> What does this have to do with this PR?

Not much :-) Just wanted to say that we could later, in addition to the changelog infos, then supplement other version highlights.

**Comment by fritzmg** [comment]
But that already exists on contao.org

**Comment by fkaminski** [comment]
Changed the shortcode. With the parameter "historyCount" (int) you can define the number of versions from the changelog. 
The output then via tabs.

**Review by fritzmg — CHANGES_REQUESTED** [review]
As I said, I am not sure how useful this is. Besides, the information might be out of date, if the docs aren't generated and deployed at the same time a new Contao version is released.

**Comment by fkaminski** [comment]
>  ...if the docs aren't generated and deployed at the same time a new Contao version is released

 True

As you like! I just wanted to update the shortcode in any case. 
If it is not needed - just close it please.

**Comment by fkaminski** [comment]
> But that already exists on contao.org

Only as a supplement. Meant were new highlights/features that were introduced in certain versions (e.g. dark mode/favorites/ajax-Forms in 5.1). 
But as you mentioned. First of all, it has nothing to do with this PR.

**Comment by netzarbeiter** [comment]
This information belongs on the Contao website.
https://contao.org/de/funktionen

**Comment by fkaminski** [comment]
Okidoki!

**Comment by fkaminski** [comment]
With your consent, I would then close this PR, as it is not necessary for the manual.

**Pull request closed without merging**
