### PR TITLE
Add and use new Shortcode taxonomylist

### PR DESCRIPTION
**Pull request by fkaminski**
New Shortcode: taxonomylist:
Create a List with linked Pages matching one or more Taxonomy Terms (similar to the shortcode "children"). 

The Taxonomic Context could be "categories" or "tags".
(Here with Front Matter "tags:" - as discussed with @fritzmg on slack)

### CODE REVIEW

**Comment by fritzmg** [comment]
Looks great, I'll have a look at it in more detail, if I see any issues :)

**Comment by fkaminski** [comment]
As already mentioned in slack: Finding the right tag term is difficult. 
Please check this regardless of the shortcode ...

**Comment by fritzmg** [comment]
The shortcode looks good. I made a small change to fix the invalid HTML.

**Comment by fkaminski** [comment]
Thank you

**Comment by fkaminski** [comment]
I wanted to sum up guides (like grid, SCSS, CSS, fonts etc.) with the tags term "Layout". But at the end its "Theme" - right? Same for "Seitenlayout". To reduce the number of tags i would like to use only these: 

Theme, Modul, Seitenstruktur, Template

What do you think?

**Comment by netzarbeiter** [comment]
I like

**Comment by Toflar** [comment]
Nice!

**Pull request merged**
