### PR TITLE
Add Guide: Basic Animation

### PR DESCRIPTION
**Pull request by fkaminski**
| Info |
| --- |
| see Issue #606 |

### CODE REVIEW

**Comment by fritzmg** [comment]
I still think that things like this should not really be in the manual as it has nothing to do with Contao. The title says "Animationen in Contao" - but I do not see anything specific to Contao in that guide. The Contao Manual is the manual for... Contao. It's not supposed to be a dumping ground for anything you can do with HTML, CSS and JavaScript?

**Comment by fkaminski** [comment]
Extensions like "[inspiredminds/contao-wowjs](https://extensions.contao.org/?q=wow&pages=1&p=inspiredminds%2Fcontao-wowjs)" or "[hypergalactic/contao-animate](https://extensions.contao.org/?p=hypergalaktisch%2Fcontao-animate)" contain corresponding possibilities. 

It is correct: These instructions do not contain concrete (Contao) solutions but help the general understanding. Furthermore, this reveals the wide range of possibilities with Contao.

Otherwise, some instructions would be superfluous altogether (svg/sass/webfont).

**Comment by fritzmg** [comment]
> Furthermore, this reveals the wide range of possibilities with Contao.

But it's not specific to Contao? It's just what you can generally do in web development.

> Otherwise, some instructions would be superfluous altogether (svg/sass/webfont).

As I said, I don't think any of this should actually be in the Contao manual ;)

**Comment by fkaminski** [comment]
As always - Only one/my suggestion. 
Ultimately your decision ...

**Comment by fkaminski** [comment]
Shall we close that then? Possibly rather something for a forum post ...

**Comment by netzarbeiter** [comment]
As suggested I close this pull request and would be happy about a forum post instead.

**Pull request closed without merging**
