### PR TITLE
Use security voters instead of user instances

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by fritzmg** [comment]
Does this work in Contao 4.4 as well?

Also the downside to doing it like this is that you still have to fetch the user afterwards, whereas before you already had the user.

**Comment by aschempp** [comment]
no this will not work in Contao 4.4, because it does not use Symfony Security.
Why would you fetch the user afterwards?

**Comment by fritzmg** [comment]
Well in most of my use cases I need information about the user, but may be not in all use cases, yeah.

**Comment by fritzmg** [comment]
Thank you @aschempp :)

**Pull request merged**
