### PR TITLE
Add Shortcode Tabbed-View Info

### PR DESCRIPTION
**Pull request by fkaminski**
...

### CODE REVIEW

**Comment by fritzmg** [comment]
Why do you want to add this? If you just want to show a single code example it makes no sense to put it in a tab?

Generally it would help if you provide more information for a Pull Request, not just "…" ;)

**Comment by fkaminski** [comment]
> Why do you want to add this? If you just want to show a single code example it makes no sense to put it in a tab?

I thought now that this function is available it would be nice if everyone is informed about it

**Comment by fkaminski** [comment]
> Generally it would help if you provide more information for a Pull Request, not just "…" ;)

OK (But this time there was nothing more to say than already in the headline) ...

**Comment by fritzmg** [comment]
> I thought now that this function is available it would be nice if everyone is informed about it

You are trying to create a new rule though, rather than just informing people about a new feature of the theme. As such it does not make sense, since you should definitely not use a tab for a single code example (in my opinion).

The CONTRIBUTING.md does not list all the features of the theme, nor does it have to. It already says the following:

> See learn.netlify.com/en/cont/markdown/ and learn.netlify.com/en/shortcodes/ for available markdown and shortcode syntax.

**Comment by fritzmg** [comment]
> But this time there was nothing more to say than already in the headline

I disagree, you always need to explain _why_ you want to make any change.

**Comment by fkaminski** [comment]
Ok, understood.
Closed this.

**Pull request closed without merging**
