### PR TITLE
Hint about CompilerPass in ExtensionPluginInterface

### PR DESCRIPTION
**Pull request by Toflar**
I don't know why it does not work but it doesn't. I guess @aschempp has to provide the reason here :)

### CODE REVIEW

**Comment by aschempp** [comment]
Can you elaborate on what _does not work_?

**Comment by aschempp** [comment]
Also, adding a compiler pass in a manager plugin - especially in the interface method that is designed to override other bundle config - makes no sense. Use the bundle as usual for that, then it also works for non-managed setups.

**Comment by Toflar** [comment]
I don't have a bundle. I need to make a service public in my app.

The compiler pass is never called.

**Comment by Toflar** [comment]
Does not work:

```php
    public function getExtensionConfig($extensionName, array $extensionConfigs, ContainerBuilder $container)
    {
        $container->addCompilerPass(new class implements CompilerPassInterface {
            public function process(\Symfony\Component\DependencyInjection\ContainerBuilder $container)
            {
                dd('test');
            }
        });
    }
```

Works:

```php
    public function registerContainerConfiguration(LoaderInterface $loader, array $managerConfig)
    {
        $loader->load(static function (ContainerBuilder $container) {
            $container->addCompilerPass(new class implements CompilerPassInterface {
                public function process(\Symfony\Component\DependencyInjection\ContainerBuilder $container)
                {
                    dd('test');
                }
            });
        });
    }
 ```

**Comment by aschempp** [comment]
`getExtensionConfig` is executed by the `MergeConfigurationPass`. I think you _could_ probably add a compiler pass that is run after merge, but adding a compiler pass in the plugin should only be done for edge cases in the app, not in any bundle. Not sure I would really recommend that here.

**Comment by Toflar** [comment]
I've updated the description and extended the examples to show why it's correct and desired to have a compiler pass in your app **without** any bundle.

**Review by fritzmg — APPROVED** [review]
Very nice! 👍

**Review by m-vo — APPROVED** [review]

**Comment by m-vo** [comment]
Same thing will be needed to adjust the virtual filesystem stuff in the app. Feels like I'll probably add another example to this section soon. :smile:

**Pull request merged**
