### PR TITLE
TopNavigation and sticky top-bar

### PR DESCRIPTION
**Pull request by fkaminski**
Quickfix #1423

### CODE REVIEW

**Review by netzarbeiter — APPROVED** [review]
Thank you, Franko

**Comment by fritzmg** [comment]
That makes the top bar jump though.

**Comment by lukasbableck** [comment]
The top bar also overlaps the search overlay a little bit now 

image

**Comment by fritzmg** [comment]
@fkaminski should we revert https://github.com/contao/docs/pull/1416 and https://github.com/contao/docs/issues/1423 instead for the time being?

**Comment by fkaminski** [comment]
> @fkaminski should we revert #1416 and #1423 instead for the time being?

As you like. 
We could fix the `.DocSearch-Modal` class with a custom `top: 34px;` too? 

It would be better in the long term to remove the “`jquery.sticky.js`” and use a pure custom CCS solution. But the “`jquery.sticky.js`” is part of the **theme** partial (footer.html) and it would probably be more difficult to maintain it.

**Comment by fritzmg** [comment]
> We could fix the `.DocSearch-Modal` class with a custom `top: 34px;` too?

I guess that will be sufficient. But I still don't like the sudden jump of the top bar.

**Comment by fkaminski** [comment]
> ... But I still don't like the sudden jump of the top bar.

Me too. But as mentioned, unfortunately we can currently only overwrite (css !important) the inline style from the theme script without touching the theme assets

**Comment by fritzmg** [comment]
Fixed in 65b47d6

**Pull request merged**
