### PR TITLE
Extend the environment variables with APP_SECRET and DATABASE_URL descriptions

### PR DESCRIPTION
**Pull request by qzminski**
/cc @aschempp

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]
LGTM, though I haven't really tested/used these myself yet (in a Contao Managed Edition - I do use them in regular Symfony applications). I take it they do work in the Contao Managed Edition?

**Comment by aschempp** [comment]
They work in Contao 4.9 and the `parameters.yml` is deprecated in favor of env variables. Both work, but you obviously shouldn't mix them 😆

**Review by aschempp — CHANGES_REQUESTED** [review]
Maybe we should add an info that this only works in 4.9 and one should not define the respective parameters then?

**Comment by fritzmg** [comment]
So just adding `{{< version "4.8" >}}` to `APP_SECRET` and `DATABASE_URL`, is that correct? Plus may be a `{{% notice info %}}` to not mix env and parameters.

**Comment by aschempp** [comment]
Yeah, I guess that's up to you (@fritzmg) 😂 
I didn't use the version tag in my docs, I simply added a note with the same text and some extensive info. Example: https://github.com/contao/docs/pull/228/files#diff-5e7f17e304650b2688078f82ec27a731R49

**Comment by fritzmg** [comment]
Hm, well @Toflar only tagged the `COOKIE_WHITELIST` with `{{< version "4.8" >}}`. Do any environment variables work before 4.8 actually?

**Comment by aschempp** [comment]
Yes, we've added some in 4.6 already: https://github.com/contao/contao/blob/4.6/manager-bundle/src/Resources/skeleton/web/app.php#L34. But before Contao 4.8 you couldn't use the `.env` file (out of the box)

**Comment by fritzmg** [comment]
Ok, well then let's just say that all of these only work in 4.9 :)

**Comment by aschempp** [comment]
I'd be fine with that. And they are the replacement for the parameters.yml in Contao 4.9

**Comment by fritzmg** [comment]
@qzminski can you add these changes?

**Comment by qzminski** [comment]
@fritzmg sure just tell me what and where exactly, as I am not familiar with things like `{{< version "4.8" >}}` 😅

**Comment by fritzmg** [comment]
I have added some changes myself in https://github.com/contao/docs/pull/290/commits/7ae9e76b05131d8afc14a1b68bc7c6602dc43b37 . @aschempp is that about correct?

**Review by aschempp — APPROVED** [review]

**Pull request merged**
