### PR TITLE
Update dca.md

### PR DESCRIPTION
**Pull request by raum51**
adapted onload_callback in full example of tl_parts.php

The example code for onload_callback of tl_parts.php differed in section tl_parts > config and full example.

### CODE REVIEW

**Review by fiedsch — COMMENTED** [review]
This should not be required as the example also has `use Contao\Database` (at the [top of the example](https://github.com/contao/docs/blob/347051eb72559160e9bd9961651728fbc03e1134/docs/dev/guides/dca.md?plain=1#L493)) 

The usage of `use ...` and "inline class paths" might be unified though, because it is mixed throughout the examples.

**Comment by raum51** [comment]
So the better way would be to make the same usage of `use ...` in the parts > config section as in the full example (and adopt `$db = ...` and `$pid = ...`), BUT in the full example following code is missing:
```
                if (empty($pid)) {
                    return;
                }
```

**Comment by fiedsch** [comment]
I would go with using `use ...` in all places. @fritzmg or @netzarbeiter will comment on what they would recommend.

The missing `$pid` part is another issue (which I did not check).

**Review by fritzmg — APPROVED** [review]
Originally there was no use statement at all. It's just personal preference.

**Comment by fritzmg** [comment]
Thank you @raum51

**Pull request merged**
