### PR TITLE
Fixed storeFormData example to not use legacy stuff anymore

### LINKED ISSUE #214: update source code - deprecated methodes
Change `FE_USER_LOGGED_IN` and database call in  https://docs.contao.org/dev/reference/hooks/storeFormData/#example

See https://contao.slack.com/archives/CNZBHDCP4/p1578417426012200

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/docs/issues/214

### CODE REVIEW

**Comment by zonky2** [comment]
THX

**Comment by fritzmg** [comment]
`\Contao\Database` isn't actually deprecated and contains useful features, which would make the example much simpler. Instead of having to write your own `columnExistsInTable` function from scratch, you can simply use `fieldExists` of `\Contao\Database`.

**Comment by Toflar** [comment]
You shouldn't be using that class anymore anyway. Even if it's useful, just don't. I haven't used it anymore for over 4 years now. We may provide some util classes in the core someday but I just don't want the docs to contain old stuff if possible.

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Thank you @Toflar

**Comment by zonky2** [comment]
thx!

**Comment by Toflar** [comment]
@fritzmg maybe we could use `$columns = $schemaManager->listTableColumns($form->targetTable);`. Then there's no need for my "complex" separate method.

**Pull request merged**
