### PR TITLE
Add hint to breadcrumb for schema.org

### PR DESCRIPTION
**Pull request by zonky2**
Add hint to breadcrumb for schema.org

### CODE REVIEW

**Review by netzarbeiter — APPROVED** [review]
Thank you, Ingolf

**Comment by fritzmg** [comment]
I don't quite understand these changes - @zonky2 what do you refer to here?

**Comment by zonky2** [comment]
@fritzmg 

FireShot Pro Webpage Screenshot #412 - 'Testtool für strukturierte Daten' - search google

**Comment by fritzmg** [comment]
But why do you write _The navigation path should not be inserted in the header_? What exactly do you mean by that in relation to the breadcrumb module?

**Comment by zonky2** [comment]
yes, the breadcrum module should not in block "WPHeader"

**Comment by fritzmg** [comment]
But Contao does not define a block with `itemtype="http://schema.org/WPHeader"`. How is this relevant to Contao or Contao's breadcrumb module?

**Comment by zonky2** [comment]
hmm ... for my pages `WPHeader` is defined... should this come from an extension?

**Comment by fritzmg** [comment]
Or you have a custom `fe_page`. Contao itself definitely does not define anything like that (see https://github.com/contao/contao/blob/4c21af3ae68a8d41ed88b9778d94b9f8c151a386/core-bundle/src/Resources/contao/templates/frontend/fe_page.html5#L33-L37 for instance). Contao only defines `itemtype="http://schema.org/WebPage"` on the `<body>`.

**Comment by zonky2** [comment]
ohh f*** see https://github.com/contao-bootstrap/layout/blob/7c3cc8a79a849b6c9e7ece444ba12e6668f1d0aa/src/Resources/contao/templates/fe_bootstrap.html5#L41

sorry - we can remove the commit again?

**Comment by zonky2** [comment]
thx for your watchful eye

**Pull request merged**
